name: Update item data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    paths:
      # if we change any of the tools that generate data, check
      - "scripts/**"
      - update.sh
      - "community_sourced_data/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  update-tz-data:
    name: Update item data using Python 3.x
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install -U "apsw>=3.43.1.1" "msgspec>=0.18.4" "aiohttp>=3.9.3"

      - name: Run update script
        run: |
          ${PWD}/update.sh

      - name: Check if item data has been updated
        id: diff-check
        run: |
          git diff --exit-code wakautosolver/data/ || echo "CHANGE=true" >> "${GITHUB_OUTPUT}"

      - name: Commit and PR changes
        if: steps.diff-check.outputs.CHANGE == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            wakautosolver/data/**
          commit-message: "Autogenerated commit for item data update"
          body: |
            Update wakautosolver/data with latest version.
          branch: update/wakautosolver/data
          title: "[Automated] Update item data"